/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab.sep;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        sqs_Receive classUnderTest = new sqs_Receive();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
